/**
 *  This file is auto-generated by StellaNowCLI. DO NOT EDIT.
 * 
 *  ID: 5b9f25e9-b173-4db1-ad12-c13a9983b70a
 *  Generated: 2025-03-18T12:43:02Z
**/

import type { ToJSON } from 'stellanow-sdk';
import { StellaNowMessageBase, Converters, EntityType } from 'stellanow-sdk';


export class UserLoginMessage extends StellaNowMessageBase implements ToJSON {
    constructor(
        public readonly patron: string,
        public readonly user_id: string,
        public readonly timestamp: Date
    ) {
        super('user_login', [new EntityType('patron', patron)]);
    }

    public toJSON(): object {
        return {
            user_id: Converters.convert(this.user_id),
            timestamp: Converters.convert(this.timestamp),
            ...super.toJSON(),
        };
    }
}
/**
 *  Generated from:
 * {
 *     "createdAt": "2025-02-28 00:25:02",
 *     "updatedAt": "2025-02-28 00:27:21",
 *     "id": "5b9f25e9-b173-4db1-ad12-c13a9983b70a",
 *     "name": "user_login",
 *     "projectId": "4c9450e5-1a6e-4ab4-8b1d-43e9c2a40714",
 *     "isActive": true,
 *     "description": "",
 *     "fields": [
 *         {
 *             "id": "7cdb9210-1d59-43ba-94d1-ffbc2dc34c50",
 *             "name": "user_id",
 *             "fieldType": {
 *                 "value": "String"
 *             },
 *             "required": true,
 *             "subfields": []
 *         },
 *         {
 *             "id": "cc2a9651-edbb-4864-b09b-af0914b9349b",
 *             "name": "timestamp",
 *             "fieldType": {
 *                 "value": "DateTime"
 *             },
 *             "required": true,
 *             "subfields": []
 *         }
 *     ],
 *     "entities": [
 *         {
 *             "id": "5ed0f3c9-e3a1-417c-b0da-277d863d88f1",
 *             "name": "patron"
 *         }
 *     ]
 * }
**/