name: Create Release and Publish to npm

on:
  push:
    branches:
      - master
      - stable-prep

jobs:
  build-and-publish:
    name: Build, Test, and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure full history for tagging

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' # Use a recent Node.js version; adjust as needed
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm ci # Use 'ci' for consistent dependency installation

      - name: Build
        run: npm run build

      - name: Run Tests
        run: npm run test

      - name: Setup Git User
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Extract Version and Tag Commit
        run: |
          version=$(node -p "require('./package.json').version")
          tag_name="v$version"
          git tag -a "$tag_name" -m "Release $version"
          git push origin "$tag_name"
          echo "VERSION=$version" >> $GITHUB_ENV
          echo "TAG_NAME=$tag_name" >> $GITHUB_ENV

      - name: Check If Prerelease
        id: prerelease
        run: |
          echo "PRERELEASE=$(echo ${{ env.VERSION }} | grep -q '-' && echo true || echo false)" >> $GITHUB_ENV
        shell: bash

      - name: Create a New Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.VERSION }}
          body: |
            ${{ github.event.head_commit.message }}
          draft: false
          prerelease: ${{ env.PRERELEASE }}

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
